### ISSUE TITLE
Modulsuche ist nicht kompatibel mit Bloecks

### ISSUE THREAD

**Issue by ritzfritz** [FriendsOfREDAXO/modulsuche#2]
Nach kopieren wird einfügen nicht angeboten.

**Comment by ascky-thorben** [comment]
Das war bei mir vorerst auch ein Problem:
https://github.com/FriendsOfREDAXO/module_preview/blob/9e5ac57862c9bd3aeda2d233227c2b2abda6087b/boot.php#L13
Und
https://github.com/FriendsOfREDAXO/module_preview/blob/9e5ac57862c9bd3aeda2d233227c2b2abda6087b/lib/module_preview.php#L60

**Comment by eaCe** [comment]
Das war bei mir vorerst auch ein Problem:
https://github.com/FriendsOfREDAXO/module_preview/blob/9e5ac57862c9bd3aeda2d233227c2b2abda6087b/boot.php#L13
Und
https://github.com/FriendsOfREDAXO/module_preview/blob/9e5ac57862c9bd3aeda2d233227c2b2abda6087b/lib/module_preview.php#L60
